# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# deploymentconfigs "logtofile" was not valid:
# * spec.template.spec.containers[0].volumeMounts[0].name: Not found: "tmp"
# * spec.template.spec.containers[1].volumeMounts[0].name: Not found: "tmp"
#
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2018-03-20T13:14:13Z
  generation: 4
  labels:
    app: logtofile
  name: logtofile
  namespace: tok-logging
  resourceVersion: "392685"
  selfLink: /oapi/v1/namespaces/tok-logging/deploymentconfigs/logtofile
  uid: 9581ad61-2c40-11e8-9d34-166b4f376a2c
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: logtofile
    deploymentconfig: logtofile
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: logtofile
        deploymentconfig: logtofile
    spec:
      containers:
      - image: docker.io/wkulhanek/logtofile@sha256:90624a732b17daee5deb15313f9d2a5917935018a8fa1b298e3446f226f54852
        imagePullPolicy: Always
        name: logtofile
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      - args:
        - /bin/sh
        - -c
        - sleep 5 && tail -n+1 -f /tmp/datelog.txt
        image: busybox
        imagePullPolicy: Always
        name: logging-sidecar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
    volumes:
    - emptyDir: {}
      name: tmp
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - logtofile
      from:
        kind: ImageStreamTag
        name: logtofile:latest
        namespace: tok-logging
      lastTriggeredImage: docker.io/wkulhanek/logtofile@sha256:90624a732b17daee5deb15313f9d2a5917935018a8fa1b298e3446f226f54852
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-03-20T13:56:36Z
    lastUpdateTime: 2018-03-20T13:56:36Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2018-03-20T13:56:36Z
    lastUpdateTime: 2018-03-20T13:56:38Z
    message: replication controller "logtofile-3" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 3
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
